version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: backend
    env_file:
      - ./server/.env
    ports:
      - "5000"

  client-builder:
    build:
      context: ./client
      args:
        VITE_SOCKET_SERVER_URL: ""
    container_name: client-builder
    depends_on:
      - backend
    volumes:
      - frontend-dist:/app/dist

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    depends_on:
      - backend
      - client-builder
    ports:
      - "8080:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  frontend-dist:
